#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -option caps:swapescape & 
bspc monitor -d I II III IV V VI VII VIII IX X

#TESTING
bspc monitor HDMI-1 -d '1' '2' '3' '4' '5' '6' '7' 
bspc monitor HDMI-0 -d '1' 

bspc config border_width         1
bspc config window_gap          10

bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


### Select only ONE of the following four ways to set the wallpaper.
feh --bg-scale /home/mascanho/Pictures/Wallpapers/wallpaper.jpg 
# xargs xwallpaper --stretch < ~/.cache/wall &
# ~/.fehbg &
# feh --randomize --bg-fill /usr/share/backgrounds/dtos-backgrounds/* &
# nitrogen --restore &

#### VARIABLES ####
COLORSCHEME="DoomOne"

#### AUTOSTART ####
sxhkd &
picom &
# killall nm-applet && nm-applet &
# killall volumeicon && volumeicon &
# /usr/bin/emacs --daemon &
# killall conky
# sleep 3 && conky -c "$HOME"/.config/conky/bspwm/"$COLORSCHEME"-01.conkyrc
# launch polybar
./.config/polybar/launch.sh

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               t
bspc config focus_by_distance             t
bspc config focus_follows_pointer         t
bspc config history_aware_focus           t
bspc config remove_disabled_monitors      t
bspc config merge_overlapping_monitors    t
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner



#### BSPWM coloring ####
bspc config normal_border_color           "#66a"
bspc config active_border_color	      "#1e1
bspc config focused_border_color	      "#5c"
bspc config presel_feedback_color	      "#5c"
bspc config urgent_border_color 	      "#d7"


bspc rule -a Gimp desktop='^8' state=floatiollow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#### MONITORS ####
for monitor in $(bspc query -M)
do
    # set the workspaces on each monitor to
    bspc monitor $monitor -d 1 2 3 4 5 6 7 
    #polybar hidden when fullscreen for vlcutube, mpv ...
    xdo below -t $(xdo id -n root) $(xdo idpolybar-main_$monitor)
done

# Mice bindings
# Set mouse 1 to move floating windows:
bspc config pointer_action1 move

# Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

# Mouse 3 button (right mouse) resize by corner:
bspc config pointer_action2 resize_corner
